# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'pim/kpimtextedit' : '@latest-kf6'
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'libraries/ktextaddons': '@latest-kf6'
    'libraries/kirigami-addons': '@latest-kf6'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]      
